table DIM_DRIVE_TRAIN
	lineageTag: 80a204d0-13bf-403b-a321-4d6cab929094

	column id_drive_train
		dataType: int64
		formatString: 0
		lineageTag: def059a5-d094-478f-a880-cd7997994c11
		summarizeBy: none
		sourceColumn: id_drive_train

		annotation SummarizationSetBy = Automatic

	column drivetrain
		dataType: string
		lineageTag: 95973b0f-1741-4538-a165-47c17317f18d
		summarizeBy: none
		sourceColumn: drivetrain

		annotation SummarizationSetBy = Automatic

	partition DIM_DRIVE_TRAIN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\alban.daniel_amaris\Documents\projet_perso\electric_vehicles_spec_2025.csv"),[Delimiter=",", Columns=22, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"brand", type text}, {"model", type text}, {"top_speed_kmh", Int64.Type}, {"battery_capacity_kWh", Int64.Type}, {"battery_type", type text}, {"number_of_cells", Int64.Type}, {"torque_nm", Int64.Type}, {"efficiency_wh_per_km", Int64.Type}, {"range_km", Int64.Type}, {"acceleration_0_100_s", Int64.Type}, {"fast_charging_power_kw_dc", Int64.Type}, {"fast_charge_port", type text}, {"towing_capacity_kg", Int64.Type}, {"cargo_volume_l", type text}, {"seats", Int64.Type}, {"drivetrain", type text}, {"segment", type text}, {"length_mm", Int64.Type}, {"width_mm", Int64.Type}, {"height_mm", Int64.Type}, {"car_body_type", type text}, {"source_url", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"brand", "model", "top_speed_kmh", "battery_capacity_kWh", "battery_type", "number_of_cells", "torque_nm", "efficiency_wh_per_km", "range_km", "acceleration_0_100_s", "fast_charging_power_kw_dc", "fast_charge_port", "towing_capacity_kg", "cargo_volume_l", "seats", "segment", "length_mm", "width_mm", "height_mm", "car_body_type", "source_url"}),
				    #"Doublons supprimés" = Table.Distinct(#"Colonnes supprimées"),
				    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 1, 1, Int64.Type),
				    #"Colonnes permutées" = Table.ReorderColumns(#"Index ajouté",{"Index", "drivetrain"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Colonnes permutées",{{"Index", "id_drive_train"}})
				in
				    #"Colonnes renommées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

