table DIM_MODEL
	lineageTag: 21759141-f161-466a-90e8-6dbcd947d413

	column model_id
		dataType: int64
		formatString: 0
		lineageTag: 6cd864f6-45fa-4319-b421-af8512ae7c4f
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column battery_type
		dataType: string
		lineageTag: 175d0072-7229-463c-8798-01c5ba0f02b9
		summarizeBy: none
		sourceColumn: battery_type

		annotation SummarizationSetBy = Automatic

	column fast_charge_port
		dataType: string
		lineageTag: fd4ee44b-a20b-4fb9-b797-85f530cf3989
		summarizeBy: none
		sourceColumn: fast_charge_port

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 11dac23c-83b8-4e39-894a-67507ae92f31
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column source_url
		dataType: string
		lineageTag: ddaf5cd0-9530-439b-8fd9-9db31f193718
		summarizeBy: none
		sourceColumn: source_url

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 50f73b0d-3e1a-4b3c-88b4-34001803a802
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	partition DIM_MODEL = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\alban.daniel_amaris\Documents\projet_perso\electric_vehicles_spec_2025.csv"),[Delimiter=",", Columns=22, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"brand", type text}, {"model", type text}, {"top_speed_kmh", Int64.Type}, {"battery_capacity_kWh", Int64.Type}, {"battery_type", type text}, {"number_of_cells", Int64.Type}, {"torque_nm", Int64.Type}, {"efficiency_wh_per_km", Int64.Type}, {"range_km", Int64.Type}, {"acceleration_0_100_s", Int64.Type}, {"fast_charging_power_kw_dc", Int64.Type}, {"fast_charge_port", type text}, {"towing_capacity_kg", Int64.Type}, {"cargo_volume_l", type text}, {"seats", Int64.Type}, {"drivetrain", type text}, {"segment", type text}, {"length_mm", Int64.Type}, {"width_mm", Int64.Type}, {"height_mm", Int64.Type}, {"car_body_type", type text}, {"source_url", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{
				"brand",
				"drivetrain",
				"top_speed_kmh", 
				"battery_capacity_kWh", 
				"car_body_type",
				"number_of_cells", 
				"torque_nm", 
				"efficiency_wh_per_km", 
				"range_km", 
				"acceleration_0_100_s", 
				"fast_charging_power_kw_dc", 
				"towing_capacity_kg", 
				"cargo_volume_l", 
				"length_mm", 
				"width_mm", 
				"height_mm"}),
				    #"Lignes filtrées" = Table.SelectRows(#"Colonnes supprimées", each ([model] <> "")),
				    #"Texte inséré avant le délimiteur" = Table.AddColumn(#"Lignes filtrées", "model_", 
				    each 
				        if [model] = "500e Convertible" then "500e" 
				        else if [model] = "500e Hatchback" then "500e" 
				        else if [model] = "600e Scorpionissima" then "600e" 
				        else if [model] = "600e Turismo" then "600e" 
				        else if [model] = "U5" then "U5" 
				        else if [model] = "U6" then "U6" 
				        else if [model] = "Romeo Junior Elettrica 54 kWh" then "Junior" 
				        else if [model] = "Romeo Junior Elettrica 54 kWh Veloce" then "Junior" 
				        else if [model] = "A290 Electric 180 hp" then "A290" 
				        else if [model] = "A290 Electric 220 hp" then "A290" 
				        else if [model] = "A6 Avant e-tron" then "A6 Avant" 
				        else if [model] = "A6 Avant e-tron performance" then "A6 Avant" 
				        else if [model] = "A6 Avant e-tron quattro" then "A6 Avant" 
				        else if [model] = "A6 Sportback e-tron" then "A6 Sportback" 
				        else if [model] = "A6 Sportback e-tron performance" then "A6 Sportback" 
				        else if [model] = "A6 Sportback e-tron quattro" then "A6 Sportback" 
				        else if [model] = "Q4 Sportback e-tron 40" then "Q4 Sportback" 
				        else if [model] = "Q4 Sportback e-tron 45" then "Q4 Sportback" 
				        else if [model] = "Q4 Sportback e-tron 45 quattro" then "Q4 Sportback" 
				        else if [model] = "Q4 Sportback e-tron 55 quattro" then "Q4 Sportback" 
				        else if [model] = "Q4 e-tron 40" then "Q4" 
				        else if [model] = "Q4 e-tron 45" then "Q4" 
				        else if [model] = "Q4 e-tron 45 quattro" then "Q4" 
				        else if [model] = "Q4 e-tron 55 quattro" then "Q4" 
				        else if [model] = "Q6 e-tron" then "Q6" 
				        else if [model] = "Q6 e-tron Sportback" then "Q6" 
				        else if [model] = "Q6 e-tron Sportback performance" then "Q6" 
				        else if [model] = "Q6 e-tron Sportback quattro" then "Q6" 
				        else if [model] = "Q6 e-tron performance" then "Q6" 
				        else if [model] = "Q6 e-tron quattro" then "Q6" 
				        else if [model] = "S6 Avant e-tron" then "S6" 
				        else if [model] = "S6 Sportback e-tron" then "S6" 
				        else if [model] = "SQ6 e-tron" then "SQ6" 
				        else if [model] = "SQ6 e-tron Sportback" then "SQ6" 
				        else if [model] = "e-tron GT RS" then "e-tron" 
				        else if [model] = "e-tron GT RS performance" then "e-tron" 
				        else if [model] = "e-tron GT S" then "e-tron" 
				        else if [model] = "e-tron GT quattro" then "e-tron" 
				        else if [model] = "i4 M50" then "i4" 
				        else if [model] = "i4 eDrive35" then "i4" 
				        else if [model] = "i4 eDrive40" then "i4" 
				        else if [model] = "i4 xDrive40" then "i4" 
				        else if [model] = "i5 M60 xDrive Sedan (MY25)" then "i5" 
				        else if [model] = "i5 M60 xDrive Touring (MY25)" then "i5" 
				        else if [model] = "i5 eDrive40 Sedan (MY25)" then "i5" 
				        else if [model] = "i5 eDrive40 Touring (MY25)" then "i5" 
				        else if [model] = "i5 xDrive40 Sedan (MY25)" then "i5" 
				        else if [model] = "i5 xDrive40 Touring (MY25)" then "i5" 
				        else if [model] = "i7 M70 xDrive" then "i7" 
				        else if [model] = "i7 eDrive50" then "i7" 
				        else if [model] = "i7 xDrive60" then "i7" 
				        else if [model] = "iX M70 xDrive" then "iX" 
				        else if [model] = "iX xDrive45" then "iX" 
				        else if [model] = "iX xDrive60" then "iX" 
				        else if [model] = "iX1 eDrive20" then "iX1" 
				        else if [model] = "iX1 xDrive30" then "iX" 
				        else if [model] = "iX2 eDrive20" then "iX2" 
				        else if [model] = "iX2 xDrive30" then "iX2"
				        else if [model] = "ATTO 2" then "ATTO 2"
				        else if [model] = "ATTO 3 (MY25)" then "ATTO 3"
				        else if [model] = "DOLPHIN 44.9 kWh Active" then "DOLPHIN"
				        else if [model] = "DOLPHIN 44.9 kWh Boost" then "DOLPHIN"
				        else if [model] = "DOLPHIN 60.4 kWh" then "DOLPHIN"
				        else if [model] = "DOLPHIN SURF 30 kWh Active" then "DOLPHIN SURF"
				        else if [model] = "DOLPHIN SURF 43.2 kWh Boost" then "DOLPHIN SURF"
				        else if [model] = "DOLPHIN SURF 43.2 kWh Comfort" then "DOLPHIN SURF"
				        else if [model] = "SEAL 61.4 kWh RWD Comfort" then "SEAL"
				        else if [model] = "SEAL 82.5 kWh AWD Excellence" then "SEAL"
				        else if [model] = "SEAL 82.5 kWh RWD Design" then "SEAL"
				        else if [model] = "SEAL U 71.8 kWh Comfort" then "SEAL U"
				        else if [model] = "SEAL U 87 kWh Design" then "SEAL U"
				        else if [model] = "SEALION 7 82.5 kWh AWD Design" then "SEALION 7"
				        else if [model] = "SEALION 7 82.5 kWh RWD Comfort" then "SEALION 7"
				        else if [model] = "SEALION 7 91.3 kWh AWD Excellence" then "SEALION 7"
				        else if [model] = "TANG Flagship" then "TANG"
				        else if [model] = "Born 170 kW - 59 kWh" then "Born"
				        else if [model] = "Born 170 kW - 77 kWh" then "Born"
				        else if [model] = "Born VZ" then "Born"
				        else if [model] = "Tavascan Endurance" then "Tavascan"
				        else if [model] = "Tavascan VZ" then "Tavascan"
				        else if [model] = "Lyriq 600 E4" then "Lyriq"
				        else if [model] = "e-Berlingo M 50 kWh" then "e-Berlingo"
				        else if [model] = "e-Berlingo XL 50 kWh" then "e-Berlingo"
				        else if [model] = "e-C3" then "e-C3"
				        else if [model] = "e-C3 Aircross" then "e-C3 Aircross"
				        else if [model] = "e-C4" then "e-C4"
				        else if [model] = "e-C4 54 kWh" then "e-C4"
				        else if [model] = "e-C4 X" then "e-C4 X"
				        else if [model] = "e-C4 X 54 kWh" then "e-C4 X"
				        else if [model] = "e-SpaceTourer M 50 kWh" then "e-SpaceTourer"
				        else if [model] = "e-SpaceTourer M 75 kWh" then "e-SpaceTourer"
				        else if [model] = "e-SpaceTourer XL 50 kWh" then "e-SpaceTourer"
				        else if [model] = "e-SpaceTourer XL 75 kWh" then "e-SpaceTourer"
				        else if [model] = "3 E-Tense" then "E-Tense"
				        else if [model] = "NÂ°4 E-Tense" then ""
				        else if [model] = "NÂ°8 AWD Long Range" then ""
				        else if [model] = "NÂ°8 FWD" then ""
				        else if [model] = "NÂ°8 FWD Long Range" then ""
				        else if [model] = "Spring Electric 45" then "Spring"
				        else if [model] = "Spring Electric 65" then "Spring"
				        else if [model] = "Box 31.4 kWh" then "Box"
				        else if [model] = "Box 42.3 kWh" then "Box"
				        else if [model] = "BEO 86 kWh" then "BEO"
				        else if [model] = "500e 3+1 24 kWh" then "500e"
				        else if [model] = "500e 3+1 42 kWh" then "500e"
				        else if [model] = "500e Cabrio 24 kWh" then "500e Cabrio"
				        else if [model] = "500e Cabrio 42 kWh" then "500e Cabrio"
				        else if [model] = "500e Hatchback 24 kWh" then "500e Hatchback"
				        else if [model] = "500e Hatchback 42 kWh" then "500e Hatchback"
				        else if [model] = "600e" then "600e"
				        else if [model] = "Grande Panda" then "Grande Panda"
				        else if [model] = "Capri Extended Range AWD" then "Capri"
				        else if [model] = "Capri Extended Range RWD" then "Capri"
				        else if [model] = "Capri Standard Range RWD" then "Capri"
				        else if [model] = "Explorer Extended Range AWD" then "Explorer"
				        else if [model] = "Explorer Extended Range RWD" then "Explorer"
				        else if [model] = "Explorer Standard Range RWD" then "Explorer"
				        else if [model] = "Mustang Mach-E ER AWD (MY25)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E ER AWD (MY24)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E ER RWD (MY25)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E ER RWD (MY24)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E GT (MY24)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E GT (MY25)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E Rally (MY25)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E Rally (MY24)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E SR RWD (MY24)" then "Mustang Mach-E"
				        else if [model] = "Mustang Mach-E SR RWD (MY25)" then "Mustang Mach-E"
				        else if [model] = "Puma Gen-E" then "Puma"
				        else if [model] = "e-Tourneo Courier" then "e-Tourneo"
				        else if [model] = "e-Tourneo Custom L1 160 kW" then "e-Tourneo"
				        else if [model] = "e-Tourneo Custom L1 210 kW" then "e-Tourneo"
				        else if [model] = "e-Tourneo Custom L2 160 kW" then "e-Tourneo"
				        else if [model] = "e-Tourneo Custom L2 210 kW" then "e-Tourneo"
				        else if [model] = "ORA 03 48 kWh" then "ORA"
				        else if [model] = "ORA 03 63 kWh" then "ORA"
				        else if [model] = "ORA 03 GT" then "ORA"
				        else if [model] = "ORA 07 GT" then "ORA"
				        else if [model] = "ORA 07 Pro" then "ORA"
				        else if [model] = "ORA 07 Pure" then "ORA"
				        else if [model] = "G80 Electrified Luxury" then "G80"
				        else if [model] = "GV60 Premium" then "GV60"
				        else if [model] = "GV60 Sport" then "GV60"
				        else if [model] = "GV60 Sport Plus" then "GV60"
				        else if [model] = "GV70 Electrified Sport" then "GV70"
				        else if [model] = "e:Ny1" then ""
				        else if [model] = "E-HS9 120 kWh" then "E-HS9"
				        else if [model] = "E-HS9 84 kWh" then "E-HS9"
				        else if [model] = "E-HS9 99 kWh" then "E-HS9"
				        else if [model] = "INSTER Long Range" then "INSTER"
				        else if [model] = "INSTER Standard Range" then "INSTER"
				        else if [model] = "IONIQ 5 63 kWh RWD (MY24)" then "IONIQ 5"
				        else if [model] = "IONIQ 5 84 kWh AWD (MY24)" then "IONIQ 5"
				        else if [model] = "IONIQ 5 84 kWh RWD (MY24)" then "IONIQ 5"
				        else if [model] = "IONIQ 5 N (MY24)" then "IONIQ 5"
				        else if [model] = "IONIQ 6 Long Range 2WD" then "IONIQ 6"
				        else if [model] = "IONIQ 6 Long Range AWD" then "IONIQ 6"
				        else if [model] = "IONIQ 6 Standard Range 2WD" then "IONIQ 6"
				        else if [model] = "IONIQ 9 Long Range AWD" then "IONIQ 9"
				        else if [model] = "IONIQ 9 Long Range RWD" then "IONIQ 9"
				        else if [model] = "IONIQ 9 Performance AWD" then "IONIQ 9"
				        else if [model] = "Kona Electric 48 kWh" then "Kona"
				        else if [model] = "Kona Electric 65 kWh" then "Kona"
				        else if [model] = "I-Pace EV400" then "I-Pace"
				        else if [model] = "Avenger Electric" then "Avenger"
				        else if [model] = "Compass Electric 74 kWh" then "Compass"
				        else if [model] = "Torres EVX" then "Torres"
				        else if [model] = "EV3 Long Range" then "EV3"
				        else if [model] = "EV3 Standard Range" then "EV3"
				        else if [model] = "EV4 Hatchback Long Range" then "EV4"
				        else if [model] = "EV4 Hatchback Standard Range" then "EV4"
				        else if [model] = "EV4 Sedan Long Range" then "EV4"
				        else if [model] = "EV4 Sedan Standard Range" then "EV4"
				        else if [model] = "EV6 GT" then "EV6"
				        else if [model] = "EV6 Long Range 2WD" then "EV6"
				        else if [model] = "EV6 Long Range AWD" then "EV6"
				        else if [model] = "EV6 Standard Range 2WD" then "EV6"
				        else if [model] = "EV9 76.1 kWh RWD" then "EV9"
				        else if [model] = "EV9 99.8 kWh AWD" then "EV9"
				        else if [model] = "EV9 99.8 kWh AWD GT" then "EV9"
				        else if [model] = "EV9 99.8 kWh AWD GT-Line" then "EV9"
				        else if [model] = "EV9 99.8 kWh RWD" then "EV9"
				        else if [model] = "Niro EV" then "Niro"
				        else if [model] = "Ypsilon" then "Ypsilon"
				        else if [model] = "C10" then "C10"
				        else if [model] = "T03" then "T03"
				        else if [model] = "RZ 300e" then "RZ"
				        else if [model] = "RZ 450e" then "RZ"
				        else if [model] = "UX 300e" then "UX"
				        else if [model] = "Eletre" then "Eletre"
				        else if [model] = "Eletre R" then "Eletre"
				        else if [model] = "Eletre S" then "Eletre"
				        else if [model] = "Emeya" then "Emeya"
				        else if [model] = "Emeya R" then "Emeya"
				        else if [model] = "Emeya S" then "Emeya"
				        else if [model] = "Air Grand Touring" then "Air Grand Touring"
				        else if [model] = "Air Pure RWD" then "Air Pure"
				        else if [model] = "Air Touring" then "Air Touring"
				        else if [model] = "02" then "02"
				        else if [model] = "Cyberster GT" then "Cyberster"
				        else if [model] = "Cyberster Trophy" then "Cyberster"
				        else if [model] = "4 Electric 51 kWh" then "4"
				        else if [model] = "4 Electric 64 kWh" then "4"
				        else if [model] = "4 Electric 77 kWh" then "4"
				        else if [model] = "4 Electric XPOWER" then "4"
				        else if [model] = "5 Electric Long Range" then "5"
				        else if [model] = "5 Electric Standard Range" then "5"
				        else if [model] = "S5  EV 49 kWh" then "S5"
				        else if [model] = "S5  EV 64 kWh" then "S5"
				        else if [model] = "ZS EV Long Range" then "ZS"
				        else if [model] = "ZS EV Standard Range" then "ZS"
				        else if [model] = "GranCabrio Folgore" then "GranTurismo"
				        else if [model] = "GranTurismo Folgore" then "GranTurismo"
				        else if [model] = "Grecale Folgore" then "Grecale Folgore"
				        else if [model] = "MIFA 9" then "MIFA 9"
				        else if [model] = "6e 68.8 kWh" then "6e"
				        else if [model] = "6e Long Range 80 kWh" then "6e"
				        else if [model] = "CLA 250+" then "CLA"
				        else if [model] = "CLA 350 4MATIC" then "CLA"
				        else if [model] = "EQA 250" then "EQA"
				        else if [model] = "EQA 250+" then "EQA"
				        else if [model] = "EQA 300 4MATIC" then "EQA"
				        else if [model] = "EQA 350 4MATIC" then "EQA"
				        else if [model] = "EQB 250+" then "EQB"
				        else if [model] = "EQB 300 4MATIC" then "EQB"
				        else if [model] = "EQB 350 4MATIC" then "EQB"
				        else if [model] = "EQE 300" then "EQE"
				        else if [model] = "EQE 350 4MATIC" then "EQE"
				        else if [model] = "EQE 350+" then "EQE"
				        else if [model] = "EQE 500 4MATIC" then "EQE"
				        else if [model] = "EQE AMG 43 4MATIC" then "EQE"
				        else if [model] = "EQE AMG 53 4MATIC+" then "EQE"
				        else if [model] = "EQE SUV 300" then "EQE"
				        else if [model] = "EQE SUV 350 4MATIC" then "EQE"
				        else if [model] = "EQE SUV 350+" then "EQE"
				        else if [model] = "EQE SUV 500 4MATIC" then "EQE"
				        else if [model] = "EQE SUV AMG 43 4MATIC" then "EQE"
				        else if [model] = "EQE SUV AMG 53 4MATIC+" then "EQE"
				        else if [model] = "EQS 350" then "EQS"
				        else if [model] = "EQS 450 4MATIC" then "EQS"
				        else if [model] = "EQS 450+" then "EQS"
				        else if [model] = "EQS 500 4MATIC" then "EQS"
				        else if [model] = "EQS 580 4MATIC" then "EQS"
				        else if [model] = "EQS AMG 53 4MATIC+" then "EQS"
				        else if [model] = "EQS SUV 450 4MATIC" then "EQS"
				        else if [model] = "EQS SUV 450+" then "EQS"
				        else if [model] = "EQS SUV 500 4MATIC" then "EQS"
				        else if [model] = "EQS SUV 580 4MATIC" then "EQS"
				        else if [model] = "EQS SUV Maybach 680" then "EQS"
				        else if [model] = "EQT 200 Long" then "EQT"
				        else if [model] = "EQT 200 Standard" then "EQT"
				        else if [model] = "EQV 250 Extra-Long" then "EQV"
				        else if [model] = "EQV 250 Long" then "EQV"
				        else if [model] = "EQV 300 Extra-Long" then "EQV"
				        else if [model] = "EQV 300 Long" then "EQV"
				        else if [model] = "G 580" then "G"
				        else if [model] = "eVito Tourer Extra-Long 60 kWh" then "eVito"
				        else if [model] = "eVito Tourer Long 60 kWh" then "eVito"
				        else if [model] = "eVito Tourer Long 90 kWh" then "eVito"
				        else if [model] = "Aceman E" then "Aceman"
				        else if [model] = "Aceman JCW" then "Aceman"
				        else if [model] = "Aceman SE" then "Aceman"
				        else if [model] = "Cooper E" then "Cooper"
				        else if [model] = "Cooper JCW" then "Cooper"
				        else if [model] = "Cooper SE" then "Cooper"
				        else if [model] = "Countryman E" then "Countryman"
				        else if [model] = "Countryman SE ALL4" then "Countryman"
				        else if [model] = "EL6 Long Range" then "EL6"
				        else if [model] = "EL6 Standard Range" then "EL6"
				        else if [model] = "EL7 Long Range" then "EL7"
				        else if [model] = "EL7 Standard Range" then "EL7"
				        else if [model] = "EL8 Long Range" then "EL8"
				        else if [model] = "EL8 Standard Range" then "EL8"
				        else if [model] = "ET5 Long Range" then "ET5"
				        else if [model] = "ET5 Standard Range" then "ET5"
				        else if [model] = "ET5 Touring Long Range" then "ET5"
				        else if [model] = "ET5 Touring Standard Range" then "ET5"
				        else if [model] = "ET7 Long Range" then "ET7"
				        else if [model] = "ET7 Standard Range" then "ET7"
				        else if [model] = "Ariya 63kWh" then "Ariya"
				        else if [model] = "Ariya 87kWh" then "Ariya"
				        else if [model] = "Ariya e-4ORCE 87kWh - 225 kW" then "Ariya"
				        else if [model] = "Ariya e-4ORCE 87kWh - 320 kW Nismo" then "Ariya"
				        else if [model] = "Townstar EV Passenger" then "Townstar"
				        else if [model] = "Townstar EV Passenger L2" then "Townstar"
				        else if [model] = "E5" then "E5"
				        else if [model] = "Astra Electric" then "Astra"
				        else if [model] = "Astra Sports Tourer Electric" then "Astra"
				        else if [model] = "Combo-e Life 50 kWh" then "Combo-e"
				        else if [model] = "Combo-e Life XL 50 kWh" then "Combo-e"
				        else if [model] = "Corsa Electric 50 kWh" then "Corsa"
				        else if [model] = "Corsa Electric 51 kWh" then "Corsa"
				        else if [model] = "Frontera 44 kWh" then "Frontera"
				        else if [model] = "Grandland 73 kWh" then "Grandland"
				        else if [model] = "Grandland 82 kWh" then "Grandland"
				        else if [model] = "Mokka Electric" then "Mokka"
				        else if [model] = "Zafira-e Life L2 50 kWh" then "Zafira-e"
				        else if [model] = "Zafira-e Life L2 75 kWh" then "Zafira-e"
				        else if [model] = "Zafira-e Life L3 50 kWh" then "Zafira-e"
				        else if [model] = "Zafira-e Life L3 75 kWh" then "Zafira-e"
				        else if [model] = "e-2008 50 kWh" then "e-2008"
				        else if [model] = "e-2008 54 kWh" then "e-2008"
				        else if [model] = "e-208 50 kWh" then "e-208"
				        else if [model] = "e-208 51 kWh" then "e-208"
				        else if [model] = "e-3008 73 kWh" then "e-3008"
				        else if [model] = "e-3008 73 kWh Dual Motor" then "e-3008"
				        else if [model] = "e-3008 97 kWh Long Range" then "e-3008"
				        else if [model] = "e-308" then "e-308"
				        else if [model] = "e-308 SW" then "e-308"
				        else if [model] = "e-408 58 kWh" then "e-408"
				        else if [model] = "e-5008 73 kWh" then "e-5008"
				        else if [model] = "e-5008 73 kWh Dual Motor" then "e-5008"
				        else if [model] = "e-5008 97 kWh Long Range" then "e-5008"
				        else if [model] = "e-Rifter M 50 kWh" then "e-Rifter"
				        else if [model] = "e-Rifter XL 50 kWh" then "e-Rifter"
				        else if [model] = "e-Traveller L2 50 kWh" then "e-Traveller"
				        else if [model] = "e-Traveller L2 75 kWh" then "e-Traveller"
				        else if [model] = "e-Traveller L3 50 kWh" then "e-Traveller"
				        else if [model] = "e-Traveller L3 75 kWh" then "e-Traveller"
				        else if [model] = "2 Long Range Dual Motor (MY26)" then ""
				        else if [model] = "2 Long Range Performance (MY26)" then ""
				        else if [model] = "2 Long Range Single Motor (MY26)" then ""
				        else if [model] = "2 Standard Range Single Motor (MY26)" then ""
				        else if [model] = "3 Long Range Dual motor" then ""
				        else if [model] = "3 Long Range Performance" then ""
				        else if [model] = "3 Long Range Single motor" then ""
				        else if [model] = "4 Long Range Dual Motor" then ""
				        else if [model] = "4 Long Range Single Motor" then ""
				        else if [model] = "Macan 4 Electric" then "Macan"
				        else if [model] = "Macan 4S Electric" then "Macan"
				        else if [model] = "Macan Electric" then "Macan"
				        else if [model] = "Macan Turbo Electric" then "Macan"
				        else if [model] = "Taycan" then "Taycan"
				        else if [model] = "Taycan 4" then "Taycan"
				        else if [model] = "Taycan 4 Cross Turismo" then "Taycan"
				        else if [model] = "Taycan 4 Plus" then "Taycan"
				        else if [model] = "Taycan 4S" then "Taycan"
				        else if [model] = "Taycan 4S Cross Turismo" then "Taycan"
				        else if [model] = "Taycan 4S Plus" then "Taycan"
				        else if [model] = "Taycan 4S Plus Sport Turismo" then "Taycan"
				        else if [model] = "Taycan 4S Sport Turismo" then "Taycan"
				        else if [model] = "Taycan GTS" then "Taycan"
				        else if [model] = "Taycan GTS Sport Turismo" then "Taycan"
				        else if [model] = "Taycan Plus" then "Taycan"
				        else if [model] = "Taycan Plus Sport Turismo" then "Taycan"
				        else if [model] = "Taycan Sport Turismo" then "Taycan"
				        else if [model] = "Taycan Turbo" then "Taycan"
				        else if [model] = "Taycan Turbo Cross Turismo" then "Taycan"
				        else if [model] = "Taycan Turbo GT" then "Taycan"
				        else if [model] = "Taycan Turbo GT Weissach" then "Taycan"
				        else if [model] = "Taycan Turbo S" then "Taycan"
				        else if [model] = "Taycan Turbo S Cross Turismo" then "Taycan"
				        else if [model] = "Taycan Turbo S Sport Turismo" then "Taycan"
				        else if [model] = "Taycan Turbo Sport Turismo" then "Taycan"
				        else if [model] = "4 E-Tech 40kWh 120hp" then "R4"
				        else if [model] = "4 E-Tech 52kWh 150hp" then "R4"
				        else if [model] = "5 E-Tech 40kWh 120hp" then "R5"
				        else if [model] = "5 E-Tech 40kWh 95hp" then "R5"
				        else if [model] = "5 E-Tech 52kWh 150hp" then "R5"
				        else if [model] = "Kangoo E-Tech Electric" then "Kango"
				        else if [model] = "Kangoo Grand E-Tech Electric" then "Kango"
				        else if [model] = "Megane E-Tech EV60 130hp (TU2025)" then "Megane"
				        else if [model] = "Megane E-Tech EV60 220hp (TU2025)" then "Megane"
				        else if [model] = "Scenic E-Tech EV60 170hp" then "Scenic"
				        else if [model] = "Scenic E-Tech EV87 220hp" then "Scenic"
				        else if [model] = "Spectre" then "Spectre"
				        else if [model] = "Elroq 50" then "Elroq"
				        else if [model] = "Elroq 60" then "Elroq"
				        else if [model] = "Elroq 85" then "Elroq"
				        else if [model] = "Elroq RS" then "Elroq"
				        else if [model] = "Enyaq 60" then "Enyaq"
				        else if [model] = "Enyaq 85" then "Enyaq"
				        else if [model] = "Enyaq 85x" then "Enyaq"
				        else if [model] = "Enyaq Coupe 60" then "Enyaq"
				        else if [model] = "Enyaq Coupe 85" then "Enyaq"
				        else if [model] = "Enyaq Coupe 85x" then "Enyaq"
				        else if [model] = "Enyaq Coupe RS" then "Enyaq"
				        else if [model] = "Enyaq RS" then "Enyaq"
				        else if [model] = "BE11 Long Range" then "BE11"
				        else if [model] = "BE11 Standard Range" then "BE11"
				        else if [model] = "#1 Brabus" then "#1"
				        else if [model] = "#1 Premium" then "#1"
				        else if [model] = "#1 Pro" then "#1"
				        else if [model] = "#1 Pro+" then "#1"
				        else if [model] = "#1 Pulse" then "#1"
				        else if [model] = "#1 Pure" then "#1"
				        else if [model] = "#1 Pure+" then "#1"
				        else if [model] = "#3 Brabus" then "#3"
				        else if [model] = "#3 Premium" then "#3"
				        else if [model] = "#3 Pro" then "#3"
				        else if [model] = "#3 Pro+" then "#3"
				        else if [model] = "#5 Brabus" then "#5"
				        else if [model] = "#5 Premium" then "#5"
				        else if [model] = "#5 Pro" then "#5"
				        else if [model] = "#5 Pro+" then "#5"
				        else if [model] = "#5 Pulse" then "#5"
				        else if [model] = "#5 Summit Edition" then "#5"
				        else if [model] = "Solterra AWD" then "Solterra"
				        else if [model] = "Model 3 Long Range AWD (Highland)" then "Model 3"
				        else if [model] = "Model 3 Long Range RWD (Highland)" then "Model 3"
				        else if [model] = "Model 3 Performance (Highland)" then "Model 3"
				        else if [model] = "Model 3 RWD (Highland CATL LFP64)" then "Model 3"
				        else if [model] = "Model S Dual Motor" then "Model S"
				        else if [model] = "Model S Plaid" then "Model S"
				        else if [model] = "Model X Dual Motor" then "Model X"
				        else if [model] = "Model X Plaid" then "Model X"
				        else if [model] = "Model Y Long Range AWD (Juniper)" then "Model Y"
				        else if [model] = "Model Y Long Range RWD (Juniper)" then "Model Y"
				        else if [model] = "Model Y RWD (Juniper)" then "Model Y"
				        else if [model] = "PROACE Verso L 75 kWh" then "PROACE"
				        else if [model] = "PROACE Verso M 50 kWh" then "PROACE"
				        else if [model] = "PROACE Verso M 75 kWh" then "PROACE"
				        else if [model] = "Proace City Verso Electric L1 50 kWh" then "PROACE"
				        else if [model] = "Proace City Verso Electric L2 50 kWh" then "PROACE"
				        else if [model] = "bZ4X AWD" then "bZ4X"
				        else if [model] = "bZ4X FWD" then "bZ4X"
				        else if [model] = "VF 8 Eco Extended Range" then "VF 8"
				        else if [model] = "VF 8 Plus Extended Range" then "VF 8"
				        else if [model] = "ID. Buzz LWB GTX" then "ID. Buzz"
				        else if [model] = "ID. Buzz LWB Pro" then "ID. Buzz"
				        else if [model] = "ID. Buzz NWB GTX" then "ID. Buzz"
				        else if [model] = "ID. Buzz NWB Pro" then "ID. Buzz"
				        else if [model] = "ID. Buzz NWB Pure" then "ID. Buzz"
				        else if [model] = "ID.3 GTX" then "ID.3"
				        else if [model] = "ID.3 GTX Performance" then "ID.3"
				        else if [model] = "ID.3 Pro" then "ID.3"
				        else if [model] = "ID.3 Pro S" then "ID.3"
				        else if [model] = "ID.3 Pure" then "ID.3"
				        else if [model] = "ID.4 GTX" then "ID.4"
				        else if [model] = "ID.4 Pro" then "ID.4"
				        else if [model] = "ID.4 Pro 4MOTION" then "ID.4"
				        else if [model] = "ID.4 Pure" then "ID.4"
				        else if [model] = "ID.5 GTX" then "ID.5"
				        else if [model] = "ID.5 Pro" then "ID.5"
				        else if [model] = "ID.5 Pure" then "ID.5"
				        else if [model] = "ID.7 GTX" then "ID.7"
				        else if [model] = "ID.7 Pro" then "ID.7"
				        else if [model] = "ID.7 Pro S" then "ID.7"
				        else if [model] = "ID.7 Tourer GTX" then "ID.7"
				        else if [model] = "ID.7 Tourer Pro" then "ID.7"
				        else if [model] = "ID.7 Tourer Pro S" then "ID.7"
				        else if [model] = "EC40 Single Motor (MY26)" then "EC40"
				        else if [model] = "EC40 Single Motor ER (MY26)" then "EC40"
				        else if [model] = "EC40 Twin Motor (MY26)" then "EC40"
				        else if [model] = "EC40 Twin Motor Performance (MY26)" then "EC40"
				        else if [model] = "ES90 Single Motor (MY26)" then "ES90"
				        else if [model] = "ES90 Twin Motor (MY26)" then "ES90"
				        else if [model] = "ES90 Twin Motor Performance (MY26)" then "ES90"
				        else if [model] = "EX30 Cross Country (MY26)" then "EX30"
				        else if [model] = "EX30 Single Motor (MY24-26)" then "EX30"
				        else if [model] = "EX30 Single Motor ER (MY24-26)" then "EX30"
				        else if [model] = "EX30 Twin Motor Performance (MY24-26)" then "EX30"
				        else if [model] = "EX40 Single Motor (MY26)" then "EX40"
				        else if [model] = "EX40 Single Motor ER (MY26)" then "EX40"
				        else if [model] = "EX40 Twin Motor (MY26)" then "EX40"
				        else if [model] = "EX40 Twin Motor Performance (MY26)" then "EX40"
				        else if [model] = "EX90 Single Motor (MY24-26)" then "EX90"
				        else if [model] = "EX90 Twin Motor (MY24-26)" then "EX90"
				        else if [model] = "EX90 Twin Motor Performance (MY24-26)" then "EX90"
				        else if [model] = "Free 106 kWh" then ""
				        else if [model] = "G6 AWD Performance" then "G6"
				        else if [model] = "G6 RWD Long Range" then "G6"
				        else if [model] = "G6 RWD Standard Range" then "G6"
				        else if [model] = "G9 AWD Performance" then "G9"
				        else if [model] = "G9 RWD Long Range" then "G9"
				        else if [model] = "G9 RWD Standard Range" then "G9"
				        else if [model] = "P7 AWD Performance" then "P7"
				        else if [model] = "P7 RWD Long Range" then "P7"
				        else if [model] = "P7 Wing Edition" then "P7"
				        else if [model] = "001 Long Range RWD" then "001"
				        else if [model] = "001 Performance AWD" then "001"
				        else if [model] = "001 Privilege AWD" then "001"
				        else if [model] = "7X Long Range RWD" then "7X"
				        else if [model] = "7X Performance AWD" then "7X"
				        else if [model] = "7X Premium RWD" then "7X"
				        else if [model] = "X Core RWD (MY25)" then "X"
				        else if [model] = "X Long Range RWD (MY25)" then "X"
				        else if [model] = "X Privilege AWD (MY25)" then "X"
				        else "", 
				        type text),
				    #"Colonnes permutées" = Table.ReorderColumns(#"Texte inséré avant le délimiteur",{"model", "model_", "battery_type", "fast_charge_port", "seats", "segment", "source_url"}),
				    #"Colonnes supprimées1" = Table.RemoveColumns(#"Colonnes permutées",{"model", "seats"}),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Colonnes supprimées1",{{"model_", "model"}}),
				    #"Doublons supprimés" = Table.Distinct(#"Colonnes renommées1", {"model"}),
				    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 1, 1, Int64.Type),
				    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "model_id"}}),
				    #"Colonnes permutées1" = Table.ReorderColumns(#"Colonnes renommées",{"model_id", "model", "battery_type", "fast_charge_port", "segment", "source_url"})
				in
				    #"Colonnes permutées1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

